name: ci

concurrency:
  cancel-in-progress: false
  group: ci-${{ github.ref_name }}-${{ github.event_name }}

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - v*

permissions:
  contents: read
  packages: write
  security-events: write

jobs:
  build-edge:
    if: |
      github.event_name == 'push' &&
      github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Build docker
        uses: meysam81/build-docker@main
        with:
          image-name: ghcr.io/meysam81/atlantis
          image-extra-tags: |
            ghcr.io/meysam81/atlantis:${{ github.run_id }}
            ghcr.io/meysam81/atlantis:latest
          kubescape: true
          kubescape-upload-sarif: true

  build-pr:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Build docker
        uses: meysam81/build-docker@main
        with:
          image-name: ghcr.io/meysam81/atlantis
          kubescape: true

  semantic-release:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install bun deps
        run: bun install
      - id: semantic-release
        name: Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: bunx semantic-release@v24
      - if: steps.semantic-release.outputs.version != ''
        name: Build docker
        uses: meysam81/build-docker@main
        with:
          cosign: true
          image-name: ghcr.io/${{ github.repository }}
          image-extra-tags: ghcr.io/${{ github.repository }}:${{ steps.semantic-release.outputs.version }}
          kubescape: true
          ref: ${{ steps.semantic-release.outputs.version }}
          metadata-tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
