name: ci

concurrency:
  cancel-in-progress: ${{ ! startsWith(github.ref, 'refs/tags/v') }}
  group: ci-${{ github.ref_name }}-${{ github.event_name }}

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build-edge:
    if: contains(fromJson('["push","pull_request"]'), github.event_name)
    runs-on: ubuntu-latest
    steps:
      - name: Build docker
        uses: meysam81/infra/actions/build-docker@main
        with:
          image-name: ghcr.io/meysam81/atlantis
          image-extra-tags: ghcr.io/meysam81/atlantis:${{ github.run_id }}
